### ISSUE TITLE
Create config

### ISSUE THREAD

**Issue by byzg** [shlima/translate_enum#3]
I used pure rails way for translate enums: 
```ruby
class User < ActiveRecord::Base
  enum role: [ :teacher, :coordinator ]
end
```
```yaml
pt-BR:
  activerecord:
    attributes:
      user/role:
        coordinator: Coordenador
        teacher: Professor
```
```ruby
User.human_attribute_name("role.#{@user.role}")
```

but after I want to use translate_enum without changing of my yaml to ensure human_attribute_name still  works.

I think it would be usefull to allow user to select translation path here
https://github.com/shlima/translate_enum/blob/master/lib/translate_enum/builder.rb#L28
like:

```ruby
def i18n_key
   @i18n_key ||= config.i18n_key || "#{attribute}_list"
end
```
