### ISSUE TITLE
Consider using pluralized enum for localization key

### ISSUE THREAD

**Issue by iczman** [shlima/translate_enum#5]
To better align with ActiveRecord conventions, can we considering using the plural version of the enum name as the key for the localization lookup. For example:

```yaml
en:
  activerecord:
    attributes:
      post:
        status_list: # (current naming with _list appended)
        statuses:    # (proposed change to use pluralized version)
          published: Was published
          archive: Was archived
```
